enum CostActionTypes {
  GET_COST_REQUEST = 'GET_COST_REQUEST',
  GET_COST_SUCCESS = 'GET_COST_SUCCESS',
  GET_COST_FAILURE = 'GET_COST_FAILURE',
  POST_COST_REQUEST = 'POST_COST_REQUEST',
  POST_COST_SUCCESS = 'POST_COST_SUCCESS',
  POST_COST_FAILURE = 'POST_COST_FAILURE',
  PUT_COST_REQUEST = 'PUT_COST_REQUEST',
  PUT_COST_SUCCESS = 'PUT_COST_SUCCESS',
  PUT_COST_FAILURE = 'PUT_COST_FAILURE',
  DELETE_COST_REQUEST = 'DELETE_COST_REQUEST',
  DELETE_COST_SUCCESS = 'DELETE_COST_SUCCESS',
  DELETE_COST_FAILURE = 'DELETE_COST_FAILURE',
}

export default CostActionTypes;
