enum ModeOfTransportActionTypes {
  GET_MODE_OF_TRANSPORT_REQUEST = 'GET_MODE_OF_TRANSPORT_REQUEST',
  GET_MODE_OF_TRANSPORT_SUCCESS = 'GET_MODE_OF_TRANSPORT_SUCCESS',
  GET_MODE_OF_TRANSPORT_FAILURE = 'GET_MODE_OF_TRANSPORT_FAILURE',
  POST_MODE_OF_TRANSPORT_REQUEST = 'POST_MODE_OF_TRANSPORT_REQUEST',
  POST_MODE_OF_TRANSPORT_SUCCESS = 'POST_MODE_OF_TRANSPORT_SUCCESS',
  POST_MODE_OF_TRANSPORT_FAILURE = 'POST_MODE_OF_TRANSPORT_FAILURE',
  PUT_MODE_OF_TRANSPORT_REQUEST = 'PUT_MODE_OF_TRANSPORT_REQUEST',
  PUT_MODE_OF_TRANSPORT_SUCCESS = 'PUT_MODE_OF_TRANSPORT_SUCCESS',
  PUT_MODE_OF_TRANSPORT_FAILURE = 'PUT_MODE_OF_TRANSPORT_FAILURE',
  DELETE_MODE_OF_TRANSPORT_REQUEST = 'DELETE_MODE_OF_TRANSPORT_REQUEST',
  DELETE_MODE_OF_TRANSPORT_SUCCESS = 'DELETE_MODE_OF_TRANSPORT_SUCCESS',
  DELETE_MODE_OF_TRANSPORT_FAILURE = 'DELETE_MODE_OF_TRANSPORT_FAILURE',
}

export default ModeOfTransportActionTypes;
