enum PodVarianceActionTypes {
  GET_POD_VARIANCE_REQUEST = 'GET_POD_VARIANCE_REQUEST',
  GET_POD_VARIANCE_SUCCESS = 'GET_POD_VARIANCE_SUCCESS',
  GET_POD_VARIANCE_FAILURE = 'GET_POD_VARIANCE_FAILURE',
  POST_POD_VARIANCE_REQUEST = 'POST_POD_VARIANCE_REQUEST',
  POST_POD_VARIANCE_SUCCESS = 'POST_POD_VARIANCE_SUCCESS',
  POST_POD_VARIANCE_FAILURE = 'POST_POD_VARIANCE_FAILURE',
  PUT_POD_VARIANCE_REQUEST = 'PUT_POD_VARIANCE_REQUEST',
  PUT_POD_VARIANCE_SUCCESS = 'PUT_POD_VARIANCE_SUCCESS',
  PUT_POD_VARIANCE_FAILURE = 'PUT_POD_VARIANCE_FAILURE',
  DELETE_POD_VARIANCE_REQUEST = 'DELETE_POD_VARIANCE_REQUEST',
  DELETE_POD_VARIANCE_SUCCESS = 'DELETE_POD_VARIANCE_SUCCESS',
  DELETE_POD_VARIANCE_FAILURE = 'DELETE_POD_VARIANCE_FAILURE',
}

export default PodVarianceActionTypes;
