version: '3.9'

services:

  sample:
    container_name: transit_frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/transit_frontend'
      - '/transit_frontend/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
