enum TransporterActionTypes {
  GET_TRANSPORTER_REQUEST = 'GET_TRANSPORTER_REQUEST',
  GET_TRANSPORTER_SUCCESS = 'GET_TRANSPORTER_SUCCESS',
  GET_TRANSPORTER_FAILURE = 'GET_TRANSPORTER_FAILURE',
  POST_TRANSPORTER_REQUEST = 'POST_TRANSPORTER_REQUEST',
  POST_TRANSPORTER_SUCCESS = 'POST_TRANSPORTER_SUCCESS',
  POST_TRANSPORTER_FAILURE = 'POST_TRANSPORTER_FAILURE',
  PUT_TRANSPORTER_REQUEST = 'PUT_TRANSPORTER_REQUEST',
  PUT_TRANSPORTER_SUCCESS = 'PUT_TRANSPORTER_SUCCESS',
  PUT_TRANSPORTER_FAILURE = 'PUT_TRANSPORTER_FAILURE',
  DELETE_TRANSPORTER_REQUEST = 'DELETE_TRANSPORTER_REQUEST',
  DELETE_TRANSPORTER_SUCCESS = 'DELETE_TRANSPORTER_SUCCESS',
  DELETE_TRANSPORTER_FAILURE = 'DELETE_TRANSPORTER_FAILURE',
}

export default TransporterActionTypes;
