/* eslint-disable */
export enum Paths {
  landing = '/',
  sign_in = '/sign_in',
  dashboard = '/dashboard',
  reports = '/reports',
  manual_upload = '/manual_upload',
  customer_type = `/manual_upload/customer_type`,
  excel_upload = '/excel_upload',
  forbidden = '/403',
  unauthorized = '/401',
  supplier_master = `/manual_upload/supplier`,
  customer_master = `/manual_upload/customer`,
  mode_of_transport_master = `/manual_upload/mode_of_transport`,
  item_master = `/manual_upload/item`,
  item_details = `/manual_upload/item_details`,
  transporter_details = `/manual_upload/transporter_details`,
  driver_master = `/manual_upload/driver`,
  order_details = `/manual_upload/order_details`,
  shipment_details = `/manual_upload/shipment_details`,
  shipment_details_add = `/manual_upload/shipment_details/add`,
  shipment_details_edit = `/manual_upload/shipment_details/edit`,
  cost_form = `/manual_upload/cost`,
  pod_variance = `/manual_upload/pod_variance`,
}
