export enum TokenActionTypes {
  FETCH_TOKEN_REQUEST = 'FETCH_TOKEN_REQUEST',
  FETCH_TOKEN_SUCCESS = 'FETCH_TOKEN_SUCCESS',
  FETCH_TOKEN_FAILURE = 'FETCH_TOKEN_FAILURE',
  REFRESH_TOKEN_REQUEST = 'REFRESH_TOKEN_REQUEST',
  REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS',
  REFRESH_TOKEN_FAILURE = 'REFRESH_TOKEN_FAILURE',
}
  