enum SupplierMasterActionTypes {
  GET_SUPPLIER_MASTER_REQUEST = 'GET_SUPPLIER_MASTER_REQUEST',
  GET_SUPPLIER_MASTER_SUCCESS = 'GET_SUPPLIER_MASTER_SUCCESS',
  GET_SUPPLIER_MASTER_FAILURE = 'GET_SUPPLIER_MASTER_FAILURE',
  POST_SUPPLIER_MASTER_REQUEST = 'POST_SUPPLIER_MASTER_REQUEST',
  POST_SUPPLIER_MASTER_SUCCESS = 'POST_SUPPLIER_MASTER_SUCCESS',
  POST_SUPPLIER_MASTER_FAILURE = 'POST_SUPPLIER_MASTER_FAILURE',
  PUT_SUPPLIER_MASTER_REQUEST = 'PUT_SUPPLIER_MASTER_REQUEST',
  PUT_SUPPLIER_MASTER_SUCCESS = 'PUT_SUPPLIER_MASTER_SUCCESS',
  PUT_SUPPLIER_MASTER_FAILURE = 'PUT_SUPPLIER_MASTER_FAILURE',
}

export default SupplierMasterActionTypes;
