enum ItemActionTypes {
  GET_ITEM_REQUEST = 'GET_ITEM_REQUEST',
  GET_ITEM_SUCCESS = 'GET_ITEM_SUCCESS',
  GET_ITEM_FAILURE = 'GET_ITEM_FAILURE',
  POST_ITEM_REQUEST = 'POST_ITEM_REQUEST',
  POST_ITEM_SUCCESS = 'POST_ITEM_SUCCESS',
  POST_ITEM_FAILURE = 'POST_ITEM_FAILURE',
  PUT_ITEM_REQUEST = 'PUT_ITEM_REQUEST',
  PUT_ITEM_SUCCESS = 'PUT_ITEM_SUCCESS',
  PUT_ITEM_FAILURE = 'PUT_ITEM_FAILURE',
  DELETE_ITEM_REQUEST = 'DELETE_ITEM_REQUEST',
  DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS',
  DELETE_ITEM_FAILURE = 'DELETE_ITEM_FAILURE',
}

export default ItemActionTypes;
