enum TransporterDetailsActionTypes {
  GET_TRANSPORTER_DETAILS_REQUEST = 'GET_TRANSPORTER_DETAILS_REQUEST',
  GET_TRANSPORTER_DETAILS_SUCCESS = 'GET_TRANSPORTER_DETAILS_SUCCESS',
  GET_TRANSPORTER_DETAILS_FAILURE = 'GET_TRANSPORTER_DETAILS_FAILURE',
  POST_TRANSPORTER_DETAILS_REQUEST = 'POST_TRANSPORTER_DETAILS_REQUEST',
  POST_TRANSPORTER_DETAILS_SUCCESS = 'POST_TRANSPORTER_DETAILS_SUCCESS',
  POST_TRANSPORTER_DETAILS_FAILURE = 'POST_TRANSPORTER_DETAILS_FAILURE',
  PUT_TRANSPORTER_DETAILS_REQUEST = 'PUT_TRANSPORTER_DETAILS_REQUEST',
  PUT_TRANSPORTER_DETAILS_SUCCESS = 'PUT_TRANSPORTER_DETAILS_SUCCESS',
  PUT_TRANSPORTER_DETAILS_FAILURE = 'PUT_TRANSPORTER_DETAILS_FAILURE',
  DELETE_TRANSPORTER_DETAILS_REQUEST = 'DELETE_TRANSPORTER_DETAILS_REQUEST',
  DELETE_TRANSPORTER_DETAILS_SUCCESS = 'DELETE_TRANSPORTER_DETAILS_SUCCESS',
  DELETE_TRANSPORTER_DETAILS_FAILURE = 'DELETE_TRANSPORTER_DETAILS_FAILURE',
}

export default TransporterDetailsActionTypes;
