enum ShipmentImagesActionTypes {
  GET_SHIPMENT_IMAGES_REQUEST = 'GET_SHIPMENT_IMAGES_REQUEST',
  GET_SHIPMENT_IMAGES_SUCCESS = 'GET_SHIPMENT_IMAGES_SUCCESS',
  GET_SHIPMENT_IMAGES_FAILURE = 'GET_SHIPMENT_IMAGES_FAILURE',
  RESET_SHIPMENT_IMAGES = 'RESET_SHIPMENT_IMAGES',
}

export default ShipmentImagesActionTypes;
