enum CustomerMasterActionTypes {
  GET_CUSTOMER_MASTER_REQUEST = 'GET_CUSTOMER_MASTER_REQUEST',
  GET_CUSTOMER_MASTER_SUCCESS = 'GET_CUSTOMER_MASTER_SUCCESS',
  GET_CUSTOMER_MASTER_FAILURE = 'GET_CUSTOMER_MASTER_FAILURE',
  POST_CUSTOMER_MASTER_REQUEST = 'POST_CUSTOMER_MASTER_REQUEST',
  POST_CUSTOMER_MASTER_SUCCESS = 'POST_CUSTOMER_MASTER_SUCCESS',
  POST_CUSTOMER_MASTER_FAILURE = 'POST_CUSTOMER_MASTER_FAILURE',
  PUT_CUSTOMER_MASTER_REQUEST = 'PUT_CUSTOMER_MASTER_REQUEST',
  PUT_CUSTOMER_MASTER_SUCCESS = 'PUT_CUSTOMER_MASTER_SUCCESS',
  PUT_CUSTOMER_MASTER_FAILURE = 'PUT_CUSTOMER_MASTER_FAILURE',
  DELETE_CUSTOMER_MASTER_REQUEST = 'DELETE_CUSTOMER_MASTER_REQUEST',
  DELETE_CUSTOMER_MASTER_SUCCESS = 'DELETE_CUSTOMER_MASTER_SUCCESS',
  DELETE_CUSTOMER_MASTER_FAILURE = 'DELETE_CUSTOMER_MASTER_FAILURE',
}

export default CustomerMasterActionTypes;
