enum ItemDetailActionTypes {
  GET_ITEM_DETAIL_REQUEST = 'GET_ITEM_DETAIL_REQUEST',
  GET_ITEM_DETAIL_SUCCESS = 'GET_ITEM_DETAIL_SUCCESS',
  GET_ITEM_DETAIL_FAILURE = 'GET_ITEM_DETAIL_FAILURE',
  POST_ITEM_DETAIL_REQUEST = 'POST_ITEM_DETAIL_REQUEST',
  POST_ITEM_DETAIL_SUCCESS = 'POST_ITEM_DETAIL_SUCCESS',
  POST_ITEM_DETAIL_FAILURE = 'POST_ITEM_DETAIL_FAILURE',
  PUT_ITEM_DETAIL_REQUEST = 'PUT_ITEM_DETAIL_REQUEST',
  PUT_ITEM_DETAIL_SUCCESS = 'PUT_ITEM_DETAIL_SUCCESS',
  PUT_ITEM_DETAIL_FAILURE = 'PUT_ITEM__DETAILFAILURE',
  DELETE_ITEM_DETAIL_REQUEST = 'DELETE_ITEM_DETAIL_REQUEST',
  DELETE_ITEM_DETAIL_SUCCESS = 'DELETE_ITEM_DETAIL_SUCCESS',
  DELETE_ITEM_DETAIL_FAILURE = 'DELETE_ITEM_DETAIL_FAILURE',
}

export default ItemDetailActionTypes;
