enum ManualUploadActionTypes {
  GET_MANUAL_UPLOAD_REQUEST = 'GET_MANUAL_UPLOAD_REQUES',
  GET_MANUAL_UPLOAD_SUCCESS = 'GET_MANUAL_UPLOAD_SUCCESS',
  GET_MANUAL_UPLOAD_FAILURE = 'GET_MANUAL_UPLOAD_FAILURE',
}

export default ManualUploadActionTypes;
