enum CustomerWeekDaysActionTypes {
  GET_CUSTOMER_WEEK_DAYS_REQUEST = 'GET_CUSTOMER_WEEK_DAYS_REQUEST',
  GET_CUSTOMER_WEEK_DAYS_SUCCESS = 'GET_CUSTOMER_WEEK_DAYS_SUCCESS',
  GET_CUSTOMER_WEEK_DAYS_FAILURE = 'GET_CUSTOMER_WEEK_DAYS_FAILURE',
  POST_CUSTOMER_WEEK_DAYS_REQUEST = 'POST_CUSTOMER_WEEK_DAYS_REQUEST',
  POST_CUSTOMER_WEEK_DAYS_SUCCESS = 'POST_CUSTOMER_WEEK_DAYS_SUCCESS',
  POST_CUSTOMER_WEEK_DAYS_FAILURE = 'POST_CUSTOMER_WEEK_DAYS_FAILURE',
}

export default CustomerWeekDaysActionTypes;
