enum ExcelUploadActionTypes {
  GET_EXCEL_DOWNLOAD_REQUEST = 'GET_EXCEL_DOWNLOAD_REQUEST',
  GET_EXCEL_DOWNLOAD_SUCCESS = 'GET_EXCEL_DOWNLOAD_SUCCESS',
  GET_EXCEL_DOWNLOAD_FAILURE = 'GET_EXCEL_DOWNLOAD_FAILURE',
  POST_EXCEL_UPLOAD_REQUEST = 'POST_EXCEL_UPLOAD_REQUEST',
  POST_EXCEL_UPLOAD_SUCCESS = 'POST_EXCEL_UPLOAD_SUCCESS',
  POST_EXCEL_UPLOAD_FAILURE = 'POST_EXCEL_UPLOAD_FAILURE',
}

export default ExcelUploadActionTypes;
