enum ExcelUploadActionTypes {
  POST_EXCEL_UPLOAD_REQUEST = 'POST_EXCEL_UPLOAD_REQUEST',
  POST_EXCEL_UPLOAD_SUCCESS = 'POST_EXCEL_UPLOAD_SUCCESS',
  POST_EXCEL_UPLOAD_FAILURE = 'POST_EXCEL_UPLOAD_FAILURE',
}

export default ExcelUploadActionTypes;
