enum ShipmentActionTypes {
  GET_SHIPMENT_REQUEST = 'GET_SHIPMENT_REQUEST',
  GET_SHIPMENT_SUCCESS = 'GET_SHIPMENT_SUCCESS',
  GET_SHIPMENT_FAILURE = 'GET_SHIPMENT_FAILURE',
  POST_SHIPMENT_REQUEST = 'POST_SHIPMENT_REQUEST',
  POST_SHIPMENT_SUCCESS = 'POST_SHIPMENT_SUCCESS',
  POST_SHIPMENT_FAILURE = 'POST_SHIPMENT_FAILURE',
  PUT_SHIPMENT_REQUEST = 'PUT_SHIPMENT_REQUEST',
  PUT_SHIPMENT_SUCCESS = 'PUT_SHIPMENT_SUCCESS',
  PUT_SHIPMENT_FAILURE = 'PUT_SHIPMENT_FAILURE',
  DELETE_SHIPMENT_REQUEST = 'DELETE_SHIPMENT_REQUEST',
  DELETE_SHIPMENT_SUCCESS = 'DELETE_SHIPMENT_SUCCESS',
  DELETE_SHIPMENT_FAILURE = 'DELETE_SHIPMENT_FAILURE',
}

export default ShipmentActionTypes;
