enum ReportsActionTypes {
  GET_REPORTS_REQUEST = 'GET_REPORTS_REQUEST',
  GET_REPORTS_SUCCESS = 'GET_REPORTS_SUCCESS',
  GET_REPORTS_FAILURE = 'GET_REPORTS_FAILURE',
}

export default ReportsActionTypes;
