enum OrderDetailsActionTypes {
  GET_ORDER_DETAILS_REQUEST = 'GET_ORDER_DETAILS_REQUEST',
  GET_ORDER_DETAILS_SUCCESS = 'GET_ORDER_DETAILS_SUCCESS',
  GET_ORDER_DETAILS_FAILURE = 'GET_ORDER_DETAILS_FAILURE',
  POST_ORDER_DETAILS_REQUEST = 'POST_ORDER_DETAILS_REQUEST',
  POST_ORDER_DETAILS_SUCCESS = 'POST_ORDER_DETAILS_SUCCESS',
  POST_ORDER_DETAILS_FAILURE = 'POST_ORDER_DETAILS_FAILURE',
  PUT_ORDER_DETAILS_REQUEST = 'PUT_ORDER_DETAILS_REQUEST',
  PUT_ORDER_DETAILS_SUCCESS = 'PUT_ORDER_DETAILS_SUCCESS',
  PUT_ORDER_DETAILS_FAILURE = 'PUT_ORDER_DETAILS_FAILURE',
  DELETE_ORDER_DETAILS_REQUEST = 'DELETE_ORDER_DETAILS_REQUEST',
  DELETE_ORDER_DETAILS_SUCCESS = 'DELETE_ORDER_DETAILS_SUCCESS',
  DELETE_ORDER_DETAILS_FAILURE = 'DELETE_ORDER_DETAILS_FAILURE',
}

export default OrderDetailsActionTypes;
