enum OrderLineDetailsActionTypes {
  GET_ORDER_LINE_DETAILS_REQUEST = 'GET_ORDER_LINE_DETAILS_REQUEST',
  GET_ORDER_LINE_DETAILS_SUCCESS = 'GET_ORDER_LINE_DETAILS_SUCCESS',
  GET_ORDER_LINE_DETAILS_FAILURE = 'GET_ORDER_LINE_DETAILS_FAILURE',
  POST_ORDER_LINE_DETAILS_REQUEST = 'POST_ORDER_LINE_DETAILS_REQUEST',
  POST_ORDER_LINE_DETAILS_SUCCESS = 'POST_ORDER_LINE_DETAILS_SUCCESS',
  POST_ORDER_LINE_DETAILS_FAILURE = 'POST_ORDER_LINE_DETAILS_FAILURE',
}

export default OrderLineDetailsActionTypes;
