enum DriverActionTypes {
  GET_DRIVER_REQUEST = 'GET_DRIVER_REQUEST',
  GET_DRIVER_SUCCESS = 'GET_DRIVER_SUCCESS',
  GET_DRIVER_FAILURE = 'GET_DRIVER_FAILURE',
  POST_DRIVER_REQUEST = 'POST_DRIVER_REQUEST',
  POST_DRIVER_SUCCESS = 'POST_DRIVER_SUCCESS',
  POST_DRIVER_FAILURE = 'POST_DRIVER_FAILURE',
  PUT_DRIVER_REQUEST = 'PUT_DRIVER_REQUEST',
  PUT_DRIVER_SUCCESS = 'PUT_DRIVER_SUCCESS',
  PUT_DRIVER_FAILURE = 'PUT_DRIVER_FAILURE',
  DELETE_DRIVER_REQUEST = 'DELETE_DRIVER_REQUEST',
  DELETE_DRIVER_SUCCESS = 'DELETE_DRIVER_SUCCESS',
  DELETE_DRIVER_FAILURE = 'DELETE_DRIVER_FAILURE',
}

export default DriverActionTypes;
