enum CustomerTypeActionTypes {
  GET_CUSTOMER_TYPE_REQUEST = 'GET_CUSTOMER_TYPE_REQUEST',
  GET_CUSTOMER_TYPE_SUCCESS = 'GET_CUSTOMER_TYPE_SUCCESS',
  GET_CUSTOMER_TYPE_FAILURE = 'GET_CUSTOMER_TYPE_FAILURE',
  POST_CUSTOMER_TYPE_REQUEST = 'POST_CUSTOMER_TYPE_REQUEST',
  POST_CUSTOMER_TYPE_SUCCESS = 'POST_CUSTOMER_TYPE_SUCCESS',
  POST_CUSTOMER_TYPE_FAILURE = 'POST_CUSTOMER_TYPE_FAILURE',
  PUT_CUSTOMER_TYPE_REQUEST = 'PUT_CUSTOMER_TYPE_REQUEST',
  PUT_CUSTOMER_TYPE_SUCCESS = 'PUT_CUSTOMER_TYPE_SUCCESS',
  PUT_CUSTOMER_TYPE_FAILURE = 'PUT_CUSTOMER_TYPE_FAILURE',
}

export default CustomerTypeActionTypes;
