enum CustomerTypeActionTypes {
  GET_CUSTOMER_TYPE_REQUEST = 'GET_CUSTOMER_TYPE_REQUEST',
  GET_CUSTOMER_TYPE_SUCCESS = 'GET_CUSTOMER_TYPE_SUCCESS',
  GET_CUSTOMER_TYPE_FAILURE = 'GET_CUSTOMER_TYPE_FAILURE',
}

export default CustomerTypeActionTypes;
